version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/python:3.5
    steps:
    - checkout
    - run:
        name: "Pull submodules"
        command: |
          git submodule init
          git submodule update
    - restore_cache:
        key: implementation-setup-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
    - run:
        name: "Install dependencies"
        command: |
          if [ -e venv ]; then exit; fi
          python3 -m venv venv
          . venv/bin/activate
          make init develop
    - save_cache:
        key: implementation-setup-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
        paths:
          - venv
    - run:
        name: "Run tests"
        command: |
          . venv/bin/activate
          make test
