version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/python:3.5
    steps:
    - checkout
    - restore_cache:
        key: implementation-setup-{{ .Branch }}-{{ checksum "requirements.txt" }}
    - run:
        command: |
          if [ -e venv ]; then exit; fi
          python3 -m venv venv
          . venv/bin/activate
          make init
    - save_cache:
        key: implementation-setup-{{ .Branch }}-{{ checksum "requirements.txt" }}
        paths:
          - venv
    - run:
        command: |
          . venv/bin/activate
          make test
