version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/python:3.5
    steps:
    - checkout
    - run:
        name: "Pull submodules"
        command: |
          git submodule init
          git submodule update
    - restore_cache:
        key: implementation-setup-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}-{{ checksum ".circleci/config.yml" }}
    - run:
        name: "Install dependencies"
        command: |
          if [ -e venv ]; then mv ./venv ~/venv; else python3 -m venv ~/venv; fi
          . ~/venv/bin/activate
          pip install -U pip setuptools
          make init develop
          mv ~/venv ./venv
    - save_cache:
        key: implementation-setup-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}-{{ checksum ".circleci/config.yml" }}
        paths:
          - venv
    - run:
        name: "Run tests"
        command: |
          mv ./venv ~/venv
          . ~/venv/bin/activate
          make test
